name: 'Publish Agent Skills'
description: 'Build and publish Agent Skills to an OCI registry'
inputs:
  registry:
    description: 'Registry host (e.g. ghcr.io)'
    required: true
  username:
    description: 'Registry username'
    required: true
  password:
    description: 'Registry password or token'
    required: true
  namespace:
    description: 'Registry namespace (e.g. user or org)'
    required: true
  path:
    description: 'Path to skills directory'
    required: false
    default: '.'
  base:
    description: 'Git reference for change detection'
    required: false
branding:
  icon: 'package'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
